CREATE TABLE [EntLib].[xtCategoryLog](
	[CategoryLogID] [INT] IDENTITY(1,1) NOT NULL,
	[CategoryID] [INT] NOT NULL,
	[LogID] [INT] NOT NULL,
 CONSTRAINT [PK_xtCategoryLog] PRIMARY KEY CLUSTERED 
(
	[CategoryLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]