
CREATE TABLE [Person].[ContactExtendedData](
	[ContactID] [INT] NOT NULL,
	[FieldName] [VARCHAR](50) NOT NULL,
	[FieldValue] [VARCHAR](1000) NOT NULL,
 CONSTRAINT [PK_ContactExtendedData] PRIMARY KEY CLUSTERED 
(
	[ContactID] ASC,
	[FieldName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]




