CREATE TABLE [EntLib].[xtPerfLog](
	[PerfID] [INT] IDENTITY(1,1) NOT NULL,
	[PerfNm] [VARCHAR](100) NOT NULL,
	[BeginDs] [DATETIME] NOT NULL,
	[MachineNm] [VARCHAR](32) NULL,
	[UserName] [NVARCHAR](100) NULL,
	[ElapsedMilliseconds] [INT] NOT NULL,
	[AddtlInfo] [NVARCHAR](MAX) NULL,
 CONSTRAINT [PK_xtPerfLog] PRIMARY KEY CLUSTERED 
(
	[PerfID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]